name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'
      - name: Run tests
        run: go test ./...

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add this to grant write permission to repository contents
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # This fixes the shallow clone warning
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}